### ISSUE TITLE
S1: As an unregistered player, I want to be able to register a new account with my chosen credentials (username and password) to use services that are only available to registered users.

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#1]
- [x] Upon successful player registration, the game lobby overview screen is shown and the player is automatically logged in.
- [x] Upon failure, an error is displayed and the player is redirected back to the register screen. 
- [x] Logged-in players can log out and log back into their registered profile.

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#1
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#4
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#2
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#3

Server
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#16
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#17
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#18
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#19
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#20
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#21
