### ISSUE TITLE
S8: As a player after finishing a game, I want to be able to have the option to replay a game in the same lobby or quit to the main lobby overview.

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#10]
- [x] When the game is finished, the user is redirected to the game results page.
- [x] On the game results page, the user can click on a continue playing button, where he is redirected to the player lobby he had been in previously.
- [x] On the game overview page, the user can click on a return to main lobby button. When this button is clicked the user is redirected to the lobby overview page and is removed from the lobby.

**Development Tasks**
Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#37
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#38
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#39
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#40
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#63

Server

- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#87
