### ISSUE TITLE
S9: After finishing a game, a player can view their personal statistics for the played round and view a leaderboard. The leaderboard shows the winner for the round. 

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#11]
- [x] The player can view his personal time spent in round, amounts of words combined and amount of newly discovered words (for said round). 
- [x] Every player can view the leaderboard with the winner and can view the profile icon of that player.
- [x] The players overall statistics are updated with the round statistics.
- [x] On the game results page, the winner is shown and message with either "You Win!" or "You Lose!"
- [x] On the game results page, the user can see their statistics from the played game.

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#41
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#42
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#43
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#44
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#45
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#46

Server 
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#97
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#98
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#99
