### ISSUE TITLE
S10: As a logged-in user, I want to be able to spectate an ongoing match.

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#12]
**We decided to abandon this user story**

- [x] I can enter the lobby number into an input field, to start spectating a player
- [x] The board is updated following the plays of the user in semi-real time.
- [x] When the game is finished, the spectate match finishes and I am returned to the main lobby.

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#54
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#55
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#109

Server
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#110

**Comment by Tmmn** [comment]
We have decided not to pursue this feature any further and I am therefore closing this user story.
