### ISSUE TITLE
S11: As a player I want to be able to play a game mode where you don't have infinite amounts of the base elements, and you need to strategically use what you have to reach a goal word - if you run out of elements before that, you lose

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#13]
- [x] As a player I can view the remaining amount of elements left.
- [x] Each element has a limit on their use count (e.g. one word may be used 5 times max.)
- [x] Once one player  ~~is finished /~~ has run out of words, ~~a countdown appears on screen, indicating time till judgement of the winner.~~ they have lost. The game ends as soon as everyone has lost or one person has won
- [x] The winner is decided by who reaches the goal word ~~with the least amount of words used~~ first

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#81
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#82
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#83
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#84

Server
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#153
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#154
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#155
