### ISSUE TITLE
S13: As a player I want to be able to participate in a tournament format in form of a daily challenge. The goal is to reach the target word in the fewest moves and players are ranked on a leaderboard

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#14]
- [x] There is a game mode on the lobby screen where a logged in user can participate in the daily tournament.
- [x] The daily challenge is defined by the game developers and always lasts for a full day.
- [x] Registered users can participate as players and secure a place on a leaderboard.
- [x] The leaderboard shows the fastest (fewest combinations) player per day
 
**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#85
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#86
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#87
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#88
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#93
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#94
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#95

Server
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#160
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#161
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#170
