### ISSUE TITLE
S14: Achievements for users

### ISSUE THREAD

**Issue by Tmmn** [sopra-fs24-group-41/sopra-fs24-group-41-server#172]
- [x] Registered users can collect achievements by playing
- [x] Things like playing a certain amount of rounds or discovering a certain amount of new words unlocks achievements
- [x] Achievements are displayed in the user profile

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#96
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#97

Server
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#175
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#176
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#177
