### ISSUE TITLE
S2: As a registered player, I want to be able to view and inspect my account on a profile page. On this page I can view my statistics and set a profile icon.

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#2]
- [x] **Upon profile click, the player is redirected to the profile page.**
- [x] **On the profile page, the player can choose from a set of predefined user icons as their profile icon.**
- [x] **The player can view play statistics such as overall amounts of games played, amount of words merged and games won.**
- [x] _(Optional) At certain goals, e.g. 10 Games played, new user icons are unlocked._

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#5
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#6
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#7
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#8
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#9

Server
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#26
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#28
- [x] #144
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#29
