### ISSUE TITLE
S3: As a player visiting the lobby overview screen, I want to be able to create a new game lobby to play with other players. 

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#4]
- [x] Upon successful creation or joining of a game lobby, it is checked whether the player is already registered. If not, there are options to register an account (Story 1) or to play without registering a proper account using a temporary player name. Otherwise, if the player already owns an account and is logged in, no actions by the player are required and a new game lobby instance is created.
- [x] The User is redirected to a game lobby screen.
- [x] Upon failure, an error is displayed and the player is redirected back to the lobby overview screen.
- [x] Logged-in players can always join a lobby while anonymous players have to choose a player name before entering a game.
- [x] The creator of the new game lobby is assigned the “Lobby Master” role.

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#10
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#11
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#12
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#19
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#20
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#21

Server 
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#38
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#39
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#40
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#41
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#42
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#113
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#118
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#129
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#121
- [x] #145
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#131
