### ISSUE TITLE
S4: As a player creating a Game Lobby, I want to be able to define the visibility status to classify my lobby.

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#5]
- [x] When creating a Lobby, I can decide to make it public or private.
- [x] Every public lobby is broadcast to the lobby overview screen of all online users.
- [x] A private lobby is not shown on the Lobby overview screen.
- [x] As another player, I can only join a private lobby by entering in the URL of the lobby or by entering in the game code of a lobby on the lobby overview screen.
- [x] Each lobby is assigned a game code which is shown inside of the game lobby.
- [x] The owner can change the lobby name and the visibility

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#15
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#79
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#16
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#18
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#66
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#67

Server
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#47
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#50
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#51
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#132
