### ISSUE TITLE
S5: As a player in a lobby, I want to be able to copy a lobby code that I can send to my friends so that they can join my game and we can play together.

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#6]
- [x] To allow other people to join, a unique game code is displayed that can be copied
- [x] The game room should also have a name that is displayed. This is important for players joining a public room to distinguish the rooms from each other.
- [x] To join a lobby, a player (logged-in or anonymous) can enter the lobby code into a search field or access the game directly through a shareable URL to join the lobby through a browser link.

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#22
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#23
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#24
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#25
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#80

Server
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#59
