### ISSUE TITLE
S6: As the “Lobby Master” in a lobby, I want to be able to choose the game mode and start a game.

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#7]
- [x] There are multiple icons to show all the different game modes. Upon successful choice of a game mode, the icon should be selected and the change of game mode should be broadcast to all other players currently in the same game room.
- [x] As Lobby Master, I should be the only one being able to click on a button to start the game simultaneously for all Players in that lobby. 
- [x] Upon failure, an error should be displayed with suggestions on what to do, so that a game mode can be selected.

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#26
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#27
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#28
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#30
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#29

Server

- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#65
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#66
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#67
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#68
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#69
