### ISSUE TITLE
S7: As a player in an active game, I want to be able to select two words and merge them to play the game.

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#8]
- [x] There are a certain fixed amount of initial pre-defined base words visible on the board.
- [x] The player can choose any word from a selection of words on the board.
- [x] Upon successful combination of two words, a word is created.
- [x] If the word is new, it is added to the board.
- [x] If the word has already been created by the player before, the board remains the same.
- [x] The player can use any previously created word and combine them.
- [x] The player can view and see all discovered words on the board.
- [x] Words can be merged by clicking on one element and then clicking on another element.

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#31
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#32
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#33
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#35
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#36

Server

- [x] #76
- [x] #77
- [x] #78
- [x] #79
- [x] #80
- [x] #81
- [x] #82
