### ISSUE TITLE
S12: As a player in an active Fusion Frenzy game, I want to be able to see the target word(s) to be able to combine elements to reach them as fast as possible before the other players do.

### ISSUE THREAD

**Issue by Grizzlytron** [sopra-fs24-group-41/sopra-fs24-group-41-server#9]
- [x] One or more target words are displayed in the play area
- [x] The same target word(s) are visible to everyone
- [x] If one player manages to reach the target word, all the other players get notified.
- [x] A countdown is shown on screen which indicates when the game will end, in case the target word has not been reached.

**Development Tasks**

Client
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#50
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#51
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#56
- [x] sopra-fs24-group-41/sopra-fs24-group-41-client#57

Server
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#104
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#105
- [x] sopra-fs24-group-41/sopra-fs24-group-41-server#106
- [x] #137
